name: mtfe_analyzer
description: MTFE Analyzer
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.1.0-111.0.dev <4.0.0'

dependencies:
  dartx: ^1.1.0
  intl: 0.18.1

dev_dependencies:
  lints: 3.0.0
  test: 1.24.3
